# Generated by Django 4.2.4 on 2023-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_usersavemenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menucount',
            field=models.IntegerField(default=0),
        ),
    ]
